spring:
  application:
    name: master-api-handling

server:
  port: 8989

management:
  server:
    port: 9990



httpmethods:
  retrieveResource: https://api.freeapi.app/api/v1/kitchen-sink/http-methods/get
  createResource: https://api.freeapi.app/api/v1/kitchen-sink/http-methods/post
  updateResource: https://api.freeapi.app/api/v1/kitchen-sink/http-methods/put
  partiallyUpdateResource: https://api.freeapi.app/api/v1/kitchen-sink/http-methods/patch
  deleteResource: https://api.freeapi.app/api/v1/kitchen-sink/http-methods/delete

statuscodes:
  allStatusCodeApi: https://api.freeapi.app/api/v1/kitchen-sink/status-codes
  specificStatusCodeApi: https://api.freeapi.app/api/v1/kitchen-sink/status-codes/{statusCode}

headers:
  headerInfoApi: https://api.freeapi.app/api/v1/kitchen-sink/request/headers
  clientIpAddressApi: https://api.freeapi.app/api/v1/kitchen-sink/request/ip
  userAgentApi: https://api.freeapi.app/api/v1/kitchen-sink/request/user-agent
  pathVariableApi: https://api.freeapi.app/api/v1/kitchen-sink/request/path-variable/{pathVariable}
  queryParamApi: https://api.freeapi.app/api/v1/kitchen-sink/request/query-parameter

response:
  headersApi: https://api.freeapi.app/api/v1/kitchen-sink/response/headers
  cachingApi: https://api.freeapi.app/api/v1/kitchen-sink/response/cache/{timeToLive}/{cacheResponseDirective}
  htmlCompressionApi: https://api.freeapi.app/api/v1/kitchen-sink/response/html
  xmlCompressionApi: https://api.freeapi.app/api/v1/kitchen-sink/response/xml
  gzipCompressionApi: https://api.freeapi.app/api/v1/kitchen-sink/response/gzip
  brotliCompressionApi: https://api.freeapi.app/api/v1/kitchen-sink/response/brotli
  getCookiesApi: https://api.freeapi.app/api/v1/kitchen-sink/cookies/get
  setCookiesApi: https://api.freeapi.app/api/v1/kitchen-sink/cookies/set
  removeCookiesApi: https://api.freeapi.app/api/v1/kitchen-sink/cookies/remove
  redirectUrlApi: https://api.freeapi.app/api/v1/kitchen-sink/redirect/to
  jpegDownloadApi: https://api.freeapi.app/api/v1/kitchen-sink/image/jpeg
  jpgDownloadApi: https://api.freeapi.app/api/v1/kitchen-sink/image/jpg
  pngDownloadApi: https://api.freeapi.app/api/v1/kitchen-sink/image/png
  webpDownloadApi: https://api.freeapi.app/api/v1/kitchen-sink/image/webp
  svgDownloadApi: https://api.freeapi.app/api/v1/kitchen-sink/image/svg
